import { allPermissionCodes, permissions } from "@/platform/permissions";
import type {
  DocumentTemplateConfiguration,
  PlatformState,
  RoleDefinition,
} from "@/platform/types";

export const DEMO_TENANT_ID = "tenant-demo-mona";
export const DEMO_BRAND_ID = "brand-demo-mona";
export const DEMO_WESTLANDS_BRANCH_ID = "branch-demo-westlands";
export const DEMO_NGONG_BRANCH_ID = "branch-demo-ngong-road";
export const DEMO_CURRENT_USER_ID = "user-demo-emmanuel-obiambo";

const seedTimestamp = "2026-08-18T00:00:00.000Z";

const managerPermissions = allPermissionCodes.filter(
  (permission) => permission !== permissions.settingsOrganisationManage,
);

const fullBranchCapabilities = {
  POS_ENABLED: true,
  TABLE_SERVICE: true,
  KDS_ENABLED: true,
  KITCHEN_PRINTING: true,
  BAR_PRINTING: true,
  RESERVATIONS: true,
  TAKEAWAY: true,
  DELIVERY: true,
  ONLINE_ORDERS: true,
  LOYALTY: true,
  CUSTOMER_DISPLAY: true,
  BAR_MODULE: true,
  RECEIPT_PRINTING: true,
  INVOICE_PRINTING: true,
};

const compactBranchCapabilities = {
  ...fullBranchCapabilities,
  KDS_ENABLED: false,
  RESERVATIONS: false,
  DELIVERY: false,
  ONLINE_ORDERS: false,
  CUSTOMER_DISPLAY: false,
  BAR_MODULE: false,
};

const role = (
  id: string,
  code: string,
  name: string,
  rolePermissions: string[],
): RoleDefinition => ({
  id,
  tenantId: DEMO_TENANT_ID,
  code,
  name,
  active: true,
  permissions: rolePermissions,
});

const template = (
  documentType: string,
  width: DocumentTemplateConfiguration["width"],
): DocumentTemplateConfiguration => ({
  id: `template-demo-${documentType.toLowerCase().replaceAll("_", "-")}`,
  tenantId: DEMO_TENANT_ID,
  documentType,
  width,
  copies: 1,
  showLogo: true,
  showBranch: true,
  showCashier: true,
  showCustomer: documentType !== "KOT" && documentType !== "BAR_TICKET",
  showTax: ["BILL", "RECEIPT", "INVOICE"].includes(documentType),
  showPayment: ["BILL", "RECEIPT", "INVOICE"].includes(documentType),
  showQrCode: documentType === "BILL",
  footerMessage: "Thank you for your business!",
  layoutVersion: "seramet-approved-v1",
  active: true,
});

export function createDefaultDemoPlatformState(): PlatformState {
  return {
    schemaVersion: 2,
    tenants: [
      {
        id: DEMO_TENANT_ID,
        slug: "mona-swahili-demo",
        legalName: "Mona Swahili Restaurant Limited",
        tradingName: "Mona Swahili",
        active: true,
        defaultCurrency: "KES",
        timezone: "Africa/Nairobi",
        locale: "en-KE",
        countryCode: "KE",
        createdAt: seedTimestamp,
        updatedAt: seedTimestamp,
      },
    ],
    brands: [
      {
        id: DEMO_BRAND_ID,
        tenantId: DEMO_TENANT_ID,
        name: "Mona Swahili",
        code: "MONA",
        active: true,
      },
    ],
    branches: [
      {
        id: DEMO_WESTLANDS_BRANCH_ID,
        tenantId: DEMO_TENANT_ID,
        brandId: DEMO_BRAND_ID,
        code: "WST",
        name: "Westlands",
        address: "Kipro Centre, Sports Road",
        phone: "0719 427 919",
        email: "info@monaswahili.co.ke",
        timezone: "Africa/Nairobi",
        currency: "KES",
        active: true,
        metadata: {
          kitchenMode: "KDS_AND_PRINTER",
          posTerminals: 2,
          capabilities: fullBranchCapabilities,
        },
      },
      {
        id: DEMO_NGONG_BRANCH_ID,
        tenantId: DEMO_TENANT_ID,
        brandId: DEMO_BRAND_ID,
        code: "NGG",
        name: "Ngong Road",
        address: "Ngong Road Branch",
        phone: "0719 427 919",
        email: "info@monaswahili.co.ke",
        timezone: "Africa/Nairobi",
        currency: "KES",
        active: true,
        metadata: {
          kitchenMode: "PRINTER_ONLY",
          posTerminals: 1,
          capabilities: compactBranchCapabilities,
        },
      },
    ],
    warehouses: [
      {
        id: "warehouse-demo-wst-main",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        code: "WST-MAIN",
        name: "Westlands Main Store",
        type: "MAIN",
        active: true,
      },
      {
        id: "warehouse-demo-wst-kitchen",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        code: "WST-KITCHEN",
        name: "Westlands Kitchen",
        type: "KITCHEN",
        active: true,
      },
      {
        id: "warehouse-demo-wst-bar",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        code: "WST-BAR",
        name: "Westlands Bar Store",
        type: "BAR",
        active: true,
      },
      {
        id: "warehouse-demo-ngg-main",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_NGONG_BRANCH_ID,
        code: "NGG-MAIN",
        name: "Ngong Road Main Store",
        type: "MAIN",
        active: true,
      },
    ],
    departments: [
      {
        id: "department-demo-foh",
        tenantId: DEMO_TENANT_ID,
        code: "FOH",
        name: "Front of House",
        active: true,
      },
      {
        id: "department-demo-kitchen",
        tenantId: DEMO_TENANT_ID,
        code: "KITCHEN",
        name: "Kitchen",
        active: true,
      },
      {
        id: "department-demo-finance",
        tenantId: DEMO_TENANT_ID,
        code: "FINANCE",
        name: "Finance",
        active: true,
      },
    ],
    stations: [
      {
        id: "station-demo-wst-kitchen",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        code: "MAIN-KITCHEN",
        name: "Main Kitchen",
        stationType: "KITCHEN",
        active: true,
      },
      {
        id: "station-demo-wst-grill",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        code: "GRILL",
        name: "Grill",
        stationType: "GRILL",
        active: true,
      },
      {
        id: "station-demo-wst-bar",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        code: "BAR",
        name: "Bar",
        stationType: "BAR",
        active: true,
      },
      {
        id: "station-demo-wst-dispatch",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        code: "DISPATCH",
        name: "Dispatch",
        stationType: "DISPATCH",
        active: true,
      },
      {
        id: "station-demo-ngg-kitchen",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_NGONG_BRANCH_ID,
        code: "MAIN-KITCHEN",
        name: "Main Kitchen",
        stationType: "KITCHEN",
        active: true,
      },
    ],
    serviceAreas: [
      {
        id: "area-demo-wst-main",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        name: "Main dining",
        active: true,
      },
      {
        id: "area-demo-ngg-main",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_NGONG_BRANCH_ID,
        name: "Main dining",
        active: true,
      },
    ],
    tables: Array.from({ length: 12 }, (_, index) => ({
      id: `table-demo-wst-${index + 1}`,
      tenantId: DEMO_TENANT_ID,
      branchId: DEMO_WESTLANDS_BRANCH_ID,
      serviceAreaId: "area-demo-wst-main",
      code: String(index + 1).padStart(2, "0"),
      seats: index % 3 === 0 ? 6 : 4,
      active: true,
    })),
    providers: [
      {
        id: "provider-daraja",
        code: "DARAJA",
        displayName: "M-Pesa Daraja",
        category: "PAYMENT",
        version: "v1",
        supportedCountries: ["KE"],
        capabilities: [
          "CREATE_PAYMENT_INTENT",
          "PAYMENT_PROMPT",
          "STK_PUSH",
          "QR_PAYMENT",
          "WEBHOOK_CONFIRMATION",
          "QUERY_TRANSACTION",
        ],
        configurationSchema: { shortcode: { type: "string" }, callbackUrl: { type: "string" } },
        secretFields: ["consumerKey", "consumerSecret", "passkey", "webhookSecret"],
        enabled: true,
      },
      {
        id: "provider-tendepay",
        code: "TENDEPAY",
        displayName: "TendePay",
        category: "PAYMENT",
        version: "v1",
        supportedCountries: ["KE"],
        capabilities: [],
        configurationSchema: {
          baseUrl: { type: "string" },
          collectionAccountId: { type: "string" },
          clearingAccountId: { type: "string" },
          settlementImportFormat: { type: "string" },
        },
        secretFields: ["apiKey", "webhookSecret"],
        enabled: true,
      },
      {
        id: "provider-pesapal",
        code: "PESAPAL",
        displayName: "Pesapal",
        category: "PAYMENT",
        version: "API 3.0",
        supportedCountries: ["KE"],
        capabilities: [
          "CREATE_PAYMENT_INTENT",
          "CARD_NOT_PRESENT",
          "PAYMENT_LINK",
          "WEBHOOK_CONFIRMATION",
          "QUERY_TRANSACTION",
          "REFUND",
          "PARTIAL_REFUND",
        ],
        configurationSchema: {
          callbackUrl: { type: "string" },
          ipnUrl: { type: "string" },
          notificationId: { type: "string" },
        },
        secretFields: ["consumerKey", "consumerSecret"],
        enabled: true,
      },
      {
        id: "provider-card-acquirer",
        code: "CARD_ACQUIRER",
        displayName: "Configured Card Acquirer",
        category: "PAYMENT",
        version: "v1",
        supportedCountries: ["KE"],
        capabilities: ["MANUAL_PAYMENT", "WEBHOOK_CONFIRMATION", "TRANSACTION_SYNC"],
        configurationSchema: { destinationAccount: { type: "string" } },
        secretFields: ["webhookSecret"],
        enabled: true,
      },
      {
        id: "provider-bank-feed",
        code: "BANK_FEED",
        displayName: "Configured Bank Feed",
        category: "PAYMENT",
        version: "v1",
        supportedCountries: ["KE"],
        capabilities: ["WEBHOOK_CONFIRMATION", "TRANSACTION_SYNC", "SETTLEMENT_SYNC"],
        configurationSchema: { destinationAccount: { type: "string" } },
        secretFields: ["webhookSecret"],
        enabled: true,
      },
      ...["Uber Eats", "Glovo", "Bolt Food"].map((displayName) => ({
        id: `provider-delivery-${displayName.toLowerCase().replaceAll(" ", "-")}`,
        code: displayName.toUpperCase().replaceAll(" ", "_"),
        displayName,
        category: "DELIVERY" as const,
        version:
          displayName === "Uber Eats"
            ? "eats-api-v2"
            : displayName === "Glovo"
              ? "partner-api-v2.0.2"
              : "partner-spec-required",
        capabilities: (displayName === "Uber Eats"
          ? [
              "RECEIVE_ORDERS",
              "GET_ORDER",
              "RECOVER_ACTIVE_ORDERS",
              "ACCEPT_ORDER",
              "REJECT_ORDER",
              "CANCEL_ORDER",
              "MARK_ORDER_READY",
              "UPDATE_READY_TIME",
              "UPDATE_ORDER_STATUS",
              "READ_STORE_STATUS",
              "UPDATE_STORE_STATUS",
              "FETCH_MENU",
              "SYNC_MENU",
              "SYNC_ITEMS",
              "SYNC_CATEGORIES",
              "SYNC_MODIFIERS",
              "SYNC_PRICES",
              "SYNC_AVAILABILITY",
              "WEBHOOK_CONFIRMATION",
              "ORDER_READY_NOTIFICATION",
            ]
          : displayName === "Glovo"
            ? [
                "RECEIVE_ORDERS",
                "GET_ORDER",
                "ACCEPT_ORDER",
                "MARK_ORDER_READY",
                "UPDATE_ORDER_STATUS",
                "ORDER_MODIFICATIONS",
                "FETCH_MENU",
                "SYNC_MENU",
                "SYNC_ITEMS",
                "SYNC_PRICES",
                "SYNC_AVAILABILITY",
                "READ_STORE_STATUS",
                "UPDATE_STORE_STATUS",
                "PAUSE_STORE",
                "WEBHOOK_CONFIRMATION",
                "SYNC_CANCELLATIONS",
                "ORDER_READY_NOTIFICATION",
              ]
            : []) as import("@/platform/types").ProviderCapability[],
        configurationSchema: {
          channelId: { type: "string" },
          acceptancePolicy: { type: "string" },
          unmappedItemPolicy: { type: "string" },
          menuSyncMode: { type: "string" },
          externalStoreId: { type: "string" },
          chainId: { type: "string" },
          webhookHeaderName: { type: "string" },
        },
        secretFields:
          displayName === "Uber Eats"
            ? ["clientId", "clientSecret"]
            : displayName === "Glovo"
              ? ["clientId", "clientSecret", "webhookToken"]
              : [],
        enabled: true,
      })),
    ],
    connections: [
      {
        id: "connection-demo-daraja-wst",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        providerId: "provider-daraja",
        environment: "SANDBOX",
        status: "CONFIGURED",
        displayName: "Westlands M-Pesa Till",
        configuration: { shortcode: "4235484" },
        secretReference: "secret://seramet/demo/daraja/westlands",
        metadata: {},
        consecutiveFailures: 0,
        createdAt: seedTimestamp,
        updatedAt: seedTimestamp,
      },
      {
        id: "connection-demo-card-acquirer",
        tenantId: DEMO_TENANT_ID,
        providerId: "provider-card-acquirer",
        environment: "SANDBOX",
        status: "SANDBOX",
        displayName: "Demo Card Settlement Feed",
        configuration: { destinationAccount: "Card clearing" },
        secretReference: "secret://seramet/demo/card-acquirer",
        metadata: {},
        consecutiveFailures: 0,
        createdAt: seedTimestamp,
        updatedAt: seedTimestamp,
      },
      {
        id: "connection-demo-bank-feed",
        tenantId: DEMO_TENANT_ID,
        providerId: "provider-bank-feed",
        environment: "SANDBOX",
        status: "SANDBOX",
        displayName: "Demo Bank Settlement Feed",
        configuration: { destinationAccount: "Operating account" },
        secretReference: "secret://seramet/demo/bank-feed",
        metadata: {},
        consecutiveFailures: 0,
        createdAt: seedTimestamp,
        updatedAt: seedTimestamp,
      },
      {
        id: "connection-demo-pesapal-wst",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        providerId: "provider-pesapal",
        environment: "SANDBOX",
        status: "CREDENTIALS_REQUIRED",
        displayName: "Westlands Pesapal Gateway",
        configuration: {
          callbackUrl: "/api/seramet/payments/pesapal/callback",
          ipnUrl: "/api/seramet/integrations/webhooks/PESAPAL/connection-demo-pesapal-wst",
          notificationId: "",
        },
        secretReference: "secret://seramet/demo/pesapal/westlands",
        metadata: {},
        consecutiveFailures: 0,
        createdAt: seedTimestamp,
        updatedAt: seedTimestamp,
      },
      ...["Uber Eats", "Glovo", "Bolt Food"].map((displayName) => ({
        id: `connection-demo-${displayName.toLowerCase().replaceAll(" ", "-")}`,
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        providerId: `provider-delivery-${displayName.toLowerCase().replaceAll(" ", "-")}`,
        environment: "SANDBOX" as const,
        status: "CONFIGURED" as const,
        displayName: `${displayName} Westlands`,
        configuration: {
          orderChannelId: `channel-demo-${displayName.toLowerCase().replaceAll(" ", "-")}`,
          channelId: `channel-demo-${displayName.toLowerCase().replaceAll(" ", "-")}`,
          acceptancePolicy: "AUTO_ACCEPT_VALID",
          unmappedItemPolicy: "AUTO_REJECT",
          menuSyncMode: "SERAMET_TO_PROVIDER",
          availabilitySyncEnabled: true,
          priceSyncEnabled: true,
          auto86Enabled: true,
          storeStatusSyncEnabled: false,
          defaultPrepMinutes: 25,
          maximumPrepMinutes: 90,
          scheduledOrderBufferMinutes: 5,
          allowScheduledOrders: true,
          settlementAccountId: "account-demo-marketplace-receivable",
          settlementAccounts: {
            bankAccountId: "account-demo-bank",
            marketplaceReceivableAccountId: "account-demo-marketplace-receivable",
            commissionExpenseAccountId: "account-demo-commission-expense",
            serviceFeeExpenseAccountId: "account-demo-adjustment-expense",
            deliveryAdjustmentAccountId: "account-demo-adjustment-expense",
            promotionExpenseAccountId: "account-demo-promotion-expense",
            refundExpenseAccountId: "account-demo-adjustment-expense",
            taxAdjustmentAccountId: "account-demo-adjustment-expense",
            otherAdjustmentAccountId: "account-demo-adjustment-expense",
          },
          currencyMinorUnitFactor: 100,
        },
        secretReference: `secret://seramet/demo/${displayName.toLowerCase().replaceAll(" ", "-")}`,
        metadata: {},
        consecutiveFailures: 0,
        createdAt: seedTimestamp,
        updatedAt: seedTimestamp,
      })),
    ],
    paymentMethods: [
      {
        id: "payment-demo-mpesa-till",
        tenantId: DEMO_TENANT_ID,
        code: "MPESA_TILL_MANUAL",
        displayName: "M-Pesa",
        category: "DIGITAL_WALLET",
        enabled: true,
        sortOrder: 10,
        requiresReference: true,
        requiresCustomer: false,
        supportsRefund: true,
        supportsSplit: true,
        providerConnectionId: "connection-demo-daraja-wst",
        settlementAccountId: "account-demo-mpesa-clearing",
        clearingAccountId: "account-demo-mpesa-clearing",
        receivableAccountId: "account-demo-customer-receivable",
        metadata: {},
      },
      {
        id: "payment-demo-mpesa-prompt",
        tenantId: DEMO_TENANT_ID,
        code: "MPESA_PROMPT",
        displayName: "M-Pesa Prompt",
        category: "DIGITAL_WALLET",
        enabled: true,
        sortOrder: 11,
        requiresReference: false,
        requiresCustomer: true,
        supportsRefund: true,
        supportsSplit: false,
        providerConnectionId: "connection-demo-daraja-wst",
        settlementAccountId: "account-demo-mpesa-clearing",
        clearingAccountId: "account-demo-mpesa-clearing",
        receivableAccountId: "account-demo-customer-receivable",
        metadata: { providerOperation: "PAYMENT_PROMPT" },
      },
      {
        id: "payment-demo-mpesa-qr",
        tenantId: DEMO_TENANT_ID,
        code: "MPESA_QR",
        displayName: "M-Pesa QR",
        category: "DIGITAL_WALLET",
        enabled: true,
        sortOrder: 12,
        requiresReference: false,
        requiresCustomer: false,
        supportsRefund: true,
        supportsSplit: false,
        providerConnectionId: "connection-demo-daraja-wst",
        settlementAccountId: "account-demo-mpesa-clearing",
        clearingAccountId: "account-demo-mpesa-clearing",
        receivableAccountId: "account-demo-customer-receivable",
        metadata: { providerOperation: "QR_PAYMENT" },
      },
      {
        id: "payment-demo-cash",
        tenantId: DEMO_TENANT_ID,
        code: "CASH",
        displayName: "Cash",
        category: "CASH",
        enabled: true,
        sortOrder: 20,
        requiresReference: false,
        requiresCustomer: false,
        supportsRefund: true,
        supportsSplit: true,
        settlementAccountId: "account-demo-cash",
        cashAccountId: "account-demo-cash",
        receivableAccountId: "account-demo-customer-receivable",
        metadata: {},
      },
      {
        id: "payment-demo-card",
        tenantId: DEMO_TENANT_ID,
        code: "CARD",
        displayName: "Card",
        category: "CARD",
        enabled: true,
        sortOrder: 30,
        requiresReference: true,
        requiresCustomer: false,
        supportsRefund: true,
        supportsSplit: true,
        settlementAccountId: "account-demo-card-clearing",
        clearingAccountId: "account-demo-card-clearing",
        receivableAccountId: "account-demo-customer-receivable",
        metadata: {},
      },
      {
        id: "payment-demo-bank",
        tenantId: DEMO_TENANT_ID,
        code: "BANK_TRANSFER",
        displayName: "Bank",
        category: "BANK_TRANSFER",
        enabled: true,
        sortOrder: 40,
        requiresReference: true,
        requiresCustomer: true,
        supportsRefund: true,
        supportsSplit: true,
        settlementAccountId: "account-demo-bank",
        clearingAccountId: "account-demo-bank",
        receivableAccountId: "account-demo-customer-receivable",
        metadata: {},
      },
      {
        id: "payment-demo-credit",
        tenantId: DEMO_TENANT_ID,
        code: "CUSTOMER_CREDIT",
        displayName: "Credit",
        category: "CREDIT",
        enabled: true,
        sortOrder: 50,
        requiresReference: false,
        requiresCustomer: true,
        supportsRefund: false,
        supportsSplit: true,
        settlementAccountId: "account-demo-customer-receivable",
        receivableAccountId: "account-demo-customer-receivable",
        metadata: { revenueAccountId: "account-demo-revenue" },
      },
      {
        id: "payment-demo-pesapal",
        tenantId: DEMO_TENANT_ID,
        code: "PESAPAL_GATEWAY",
        displayName: "Pesapal Gateway",
        category: "CARD",
        enabled: true,
        sortOrder: 35,
        requiresReference: false,
        requiresCustomer: true,
        supportsRefund: true,
        supportsSplit: true,
        providerConnectionId: "connection-demo-pesapal-wst",
        settlementAccountId: "account-demo-card-clearing",
        clearingAccountId: "account-demo-card-clearing",
        receivableAccountId: "account-demo-customer-receivable",
        metadata: { providerOperation: "PAYMENT_PROMPT" },
      },
      {
        id: "payment-demo-gift-card",
        tenantId: DEMO_TENANT_ID,
        code: "GIFT_CARD",
        displayName: "Gift Card",
        category: "VOUCHER",
        enabled: true,
        sortOrder: 60,
        requiresReference: true,
        requiresCustomer: false,
        supportsRefund: false,
        supportsSplit: true,
        settlementAccountId: "account-demo-gift-card-liability",
        receivableAccountId: "account-demo-customer-receivable",
        liabilityAccountId: "account-demo-gift-card-liability",
        metadata: { valueType: "GIFT_CARD" },
      },
      {
        id: "payment-demo-voucher",
        tenantId: DEMO_TENANT_ID,
        code: "PROMOTIONAL_VOUCHER",
        displayName: "Voucher",
        category: "VOUCHER",
        enabled: true,
        sortOrder: 61,
        requiresReference: true,
        requiresCustomer: false,
        supportsRefund: false,
        supportsSplit: true,
        settlementAccountId: "account-demo-promotion-expense",
        receivableAccountId: "account-demo-customer-receivable",
        metadata: {
          valueType: "PROMOTION",
          promotionAccountId: "account-demo-promotion-expense",
        },
      },
      {
        id: "payment-demo-loyalty",
        tenantId: DEMO_TENANT_ID,
        code: "LOYALTY_REWARD",
        displayName: "Loyalty Reward",
        category: "LOYALTY",
        enabled: true,
        sortOrder: 62,
        requiresReference: false,
        requiresCustomer: true,
        supportsRefund: false,
        supportsSplit: true,
        settlementAccountId: "account-demo-promotion-expense",
        receivableAccountId: "account-demo-customer-receivable",
        metadata: { promotionAccountId: "account-demo-promotion-expense" },
      },
    ],
    orderChannels: [
      {
        id: "channel-demo-dine-in",
        tenantId: DEMO_TENANT_ID,
        code: "DINE_IN",
        displayName: "Dine-In",
        channelType: "DINE_IN",
        enabled: true,
        requiresCustomer: false,
        requiresTable: true,
        requiresAddress: false,
        isExternallyPaid: false,
        sortOrder: 10,
        metadata: {},
      },
      {
        id: "channel-demo-take-away",
        tenantId: DEMO_TENANT_ID,
        code: "TAKE_AWAY",
        displayName: "Take Away",
        channelType: "TAKEAWAY",
        enabled: true,
        requiresCustomer: false,
        requiresTable: false,
        requiresAddress: false,
        isExternallyPaid: false,
        sortOrder: 20,
        metadata: {},
      },
      ...["Uber Eats", "Glovo", "Bolt Food"].map((displayName, index) => ({
        id: `channel-demo-${displayName.toLowerCase().replaceAll(" ", "-")}`,
        tenantId: DEMO_TENANT_ID,
        code: displayName.toUpperCase().replaceAll(" ", "_"),
        displayName,
        channelType: "MARKETPLACE" as const,
        enabled: true,
        deliveryProviderConnectionId: `connection-demo-${displayName.toLowerCase().replaceAll(" ", "-")}`,
        requiresCustomer: false,
        requiresTable: false,
        requiresAddress: false,
        isExternallyPaid: true,
        sortOrder: 30 + index * 10,
        metadata: {},
      })),
    ],
    devices: [
      {
        id: "device-demo-wst-front",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        name: "EPSON TM-T20 Front",
        deviceType: "PRINTER",
        connectionType: "OS_PRINTER",
        driver: "EPSON ESC/POS",
        address: "EPSON TM-T20 Front",
        enabled: true,
        healthStatus: "ONLINE",
        outputRoles: ["CUSTOMER_DOCUMENT", "OFFICE", "REPORT"],
        metadata: {},
      },
      {
        id: "device-demo-wst-kitchen",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        name: "EPSON TM-U220 Kitchen",
        deviceType: "PRINTER",
        connectionType: "OS_PRINTER",
        driver: "EPSON ESC/POS",
        address: "EPSON TM-U220 Kitchen",
        enabled: true,
        healthStatus: "ONLINE",
        outputRoles: ["KITCHEN"],
        metadata: {},
      },
      {
        id: "device-demo-wst-bar",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        name: "Bar Printer",
        deviceType: "PRINTER",
        connectionType: "OS_PRINTER",
        driver: "ESC/POS",
        address: "Bar Printer",
        enabled: true,
        healthStatus: "DEGRADED",
        outputRoles: ["BAR"],
        metadata: {},
      },
      {
        id: "device-demo-wst-kds",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        name: "Kitchen display",
        deviceType: "KDS",
        connectionType: "BROWSER",
        driver: "Seramet KDS",
        address: "kds://westlands/main",
        enabled: true,
        healthStatus: "ONLINE",
        outputRoles: [],
        metadata: {},
      },
      {
        id: "device-demo-ngg-front",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_NGONG_BRANCH_ID,
        name: "Ngong Front Printer",
        deviceType: "PRINTER",
        connectionType: "OS_PRINTER",
        driver: "ESC/POS",
        address: "Ngong Front Printer",
        enabled: true,
        healthStatus: "ONLINE",
        outputRoles: ["CUSTOMER_DOCUMENT", "KITCHEN", "BAR", "OFFICE", "REPORT"],
        metadata: {},
      },
    ],
    printRoutes: [
      ...["BILL", "RECEIPT", "INVOICE"].map((documentType) => ({
        id: `route-demo-wst-${documentType.toLowerCase()}`,
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        documentType,
        primaryDeviceId: "device-demo-wst-front",
        copies: 1,
        enabled: true,
      })),
      {
        id: "route-demo-wst-kot",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        documentType: "KOT",
        stationId: "station-demo-wst-kitchen",
        primaryDeviceId: "device-demo-wst-kitchen",
        fallbackDeviceId: "device-demo-wst-front",
        copies: 1,
        enabled: true,
      },
      {
        id: "route-demo-wst-bar",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        documentType: "BAR_TICKET",
        stationId: "station-demo-wst-bar",
        primaryDeviceId: "device-demo-wst-bar",
        fallbackDeviceId: "device-demo-wst-front",
        copies: 1,
        enabled: true,
      },
      {
        id: "route-demo-wst-dispatch",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        documentType: "DISPATCH_TICKET",
        stationId: "station-demo-wst-dispatch",
        primaryDeviceId: "device-demo-wst-kitchen",
        fallbackDeviceId: "device-demo-wst-front",
        copies: 1,
        enabled: true,
      },
      {
        id: "route-demo-wst-kds",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        documentType: "KDS_TICKET",
        stationId: "station-demo-wst-kitchen",
        primaryDeviceId: "device-demo-wst-kds",
        copies: 1,
        enabled: true,
      },
      {
        id: "route-demo-wst-report",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        documentType: "REPORT",
        primaryDeviceId: "device-demo-wst-front",
        copies: 1,
        enabled: true,
      },
      ...[
        "BILL",
        "RECEIPT",
        "INVOICE",
        "KOT",
        "BAR_TICKET",
        "DISPATCH_TICKET",
        "KDS_TICKET",
        "REPORT",
      ].map((documentType) => ({
        id: `route-demo-ngg-${documentType.toLowerCase()}`,
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_NGONG_BRANCH_ID,
        documentType,
        primaryDeviceId: "device-demo-ngg-front",
        copies: 1,
        enabled: true,
      })),
    ],
    documentIdentities: [
      {
        id: "identity-demo-wst",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_WESTLANDS_BRANCH_ID,
        businessName: "Mona Swahili",
        legalName: "Mona Swahili Restaurant Limited",
        address: "Kipro Centre, Sports Road",
        phone: "0719 427 919",
        email: "info@monaswahili.co.ke",
        taxNumber: "P051234567G",
        currency: "KES",
        paymentInstructions: [
          "M-Pesa Till: 4235484",
          "Bank: KCB Bank",
          "A/C Name: Mona Swahili Ltd",
          "A/C No: 1234567890",
        ],
        footerMessage: "Different Flavours, One Promise.",
        metadata: {
          receiptBrand: "SERAMET",
          payment: {
            tillNumber: "4235484",
            bankName: "KCB Bank",
            bankAccountName: "Mona Swahili Ltd",
            bankAccountNumber: "1234567890",
          },
        },
      },
      {
        id: "identity-demo-ngg",
        tenantId: DEMO_TENANT_ID,
        branchId: DEMO_NGONG_BRANCH_ID,
        businessName: "Mona Swahili",
        legalName: "Mona Swahili Restaurant Limited",
        address: "Ngong Road Branch",
        phone: "0719 427 919",
        email: "info@monaswahili.co.ke",
        taxNumber: "P051234567G",
        currency: "KES",
        paymentInstructions: ["M-Pesa Till: 654321"],
        footerMessage: "Different Flavours, One Promise.",
        metadata: {
          receiptBrand: "SERAMET",
          payment: {
            tillNumber: "654321",
            bankName: "",
            bankAccountName: "",
            bankAccountNumber: "",
          },
        },
      },
    ],
    documentTemplates: [
      template("KOT", "80mm"),
      template("BAR_TICKET", "80mm"),
      template("DISPATCH_TICKET", "80mm"),
      template("KDS_TICKET", "80mm"),
      template("REPORT", "A4"),
      template("BILL", "80mm"),
      template("RECEIPT", "80mm"),
      template("INVOICE", "A4"),
      template("ADDITION_TICKET", "80mm"),
      template("CANCEL_TICKET", "80mm"),
      template("REPRINTED_KOT", "80mm"),
    ],
    roles: [
      role("role-demo-general-manager", "GENERAL_MANAGER", "General Manager", allPermissionCodes),
      role("role-demo-branch-manager", "BRANCH_MANAGER", "Branch Manager", managerPermissions),
      role("role-demo-cashier", "CASHIER", "Cashier", [
        permissions.posAccess,
        permissions.ordersView,
        permissions.ordersCreate,
        permissions.ordersUpdate,
        permissions.ordersServe,
        permissions.paymentsRecord,
        permissions.paymentsRefundRequest,
        permissions.invoicesManage,
        permissions.invoicesView,
        permissions.invoicesCreate,
        permissions.invoicesReprint,
        permissions.receiptsView,
        permissions.receiptsReprint,
        permissions.attendanceUse,
      ]),
      role("role-demo-storekeeper", "STOREKEEPER", "Storekeeper", [
        permissions.inventoryView,
        permissions.inventoryAdjust,
        permissions.procurementView,
        permissions.procurementCreate,
        permissions.procurementReceive,
        permissions.wasteRecord,
        permissions.attendanceUse,
      ]),
      role("role-demo-chef", "CHEF", "Chef", [
        permissions.kitchenView,
        permissions.kitchenOperate,
        permissions.productionView,
        permissions.ordersServe,
        permissions.wasteRecord,
        permissions.attendanceUse,
      ]),
      role("role-demo-accountant", "ACCOUNTANT", "Accountant", [
        permissions.dashboardView,
        permissions.financeView,
        permissions.financeManage,
        permissions.accountingView,
        permissions.paymentsView,
        permissions.paymentsConfirm,
        permissions.paymentsRecord,
        permissions.paymentsReconcile,
        permissions.cashClose,
        permissions.reportsView,
        permissions.auditView,
      ]),
      role("role-demo-marketing", "MARKETING", "Website and Marketing", [
        permissions.marketingView,
        permissions.marketingManage,
        permissions.deliveryDispatch,
        permissions.attendanceUse,
      ]),
    ],
    users: [
      {
        id: DEMO_CURRENT_USER_ID,
        tenantId: DEMO_TENANT_ID,
        name: "Emmanuel Obiambo",
        active: true,
        roleIds: ["role-demo-branch-manager"],
        assignedBranchIds: [DEMO_WESTLANDS_BRANCH_ID],
        primaryBranchId: DEMO_WESTLANDS_BRANCH_ID,
      },
      {
        id: "user-demo-amina",
        tenantId: DEMO_TENANT_ID,
        name: "Amina W.",
        active: true,
        roleIds: ["role-demo-cashier"],
        assignedBranchIds: [DEMO_WESTLANDS_BRANCH_ID],
        primaryBranchId: DEMO_WESTLANDS_BRANCH_ID,
      },
    ],
    updatedAt: seedTimestamp,
  };
}
