import { z } from "zod";

const id = z.string().trim().min(1);

export const tenantSchema = z.object({
  id,
  slug: z.string().trim().min(1),
  legalName: z.string().trim().min(1),
  tradingName: z.string().trim().min(1),
  active: z.boolean(),
  defaultCurrency: z.string().trim().min(3),
  timezone: z.string().trim().min(1),
  locale: z.string().trim().min(2),
  countryCode: z.union([z.string().trim().length(2), z.literal("")]),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const branchSchema = z.object({
  id,
  tenantId: id,
  brandId: id.optional(),
  code: z.string().trim().min(1),
  name: z.string().trim().min(1),
  address: z.string(),
  phone: z.string(),
  email: z.string(),
  timezone: z.string().optional(),
  currency: z.string().optional(),
  active: z.boolean(),
  metadata: z.record(z.string(), z.unknown()),
});

export const paymentMethodSchema = z.object({
  id,
  tenantId: id,
  code: z.string().trim().min(1),
  displayName: z.string().trim().min(1),
  category: z.enum([
    "CASH",
    "DIGITAL_WALLET",
    "CARD",
    "BANK_TRANSFER",
    "CREDIT",
    "VOUCHER",
    "LOYALTY",
    "EXTERNAL",
    "CUSTOM",
  ]),
  enabled: z.boolean(),
  sortOrder: z.number(),
  requiresReference: z.boolean(),
  requiresCustomer: z.boolean(),
  supportsRefund: z.boolean(),
  supportsSplit: z.boolean(),
  providerConnectionId: id.optional(),
  settlementAccountId: id.optional(),
  metadata: z.record(z.string(), z.unknown()),
});

export const orderChannelSchema = z.object({
  id,
  tenantId: id,
  code: z.string().trim().min(1),
  displayName: z.string().trim().min(1),
  channelType: z.enum([
    "DINE_IN",
    "TAKEAWAY",
    "OWN_DELIVERY",
    "MARKETPLACE",
    "WEB",
    "QR",
    "PHONE",
    "WHATSAPP",
    "KIOSK",
    "OTHER",
  ]),
  enabled: z.boolean(),
  deliveryProviderConnectionId: id.optional(),
  requiresCustomer: z.boolean(),
  requiresTable: z.boolean(),
  requiresAddress: z.boolean(),
  isExternallyPaid: z.boolean(),
  sortOrder: z.number(),
  metadata: z.record(z.string(), z.unknown()),
});

export const roleSchema = z.object({
  id,
  tenantId: id,
  code: z.string().trim().min(1),
  name: z.string().trim().min(1),
  active: z.boolean(),
  permissions: z.array(z.string().trim().min(1)),
});

export const integrationConnectionSchema = z.object({
  id,
  tenantId: id,
  branchId: id.optional(),
  providerId: id,
  environment: z.enum(["SANDBOX", "PRODUCTION"]),
  status: z.enum([
    "UNCONFIGURED",
    "CREDENTIALS_REQUIRED",
    "CONFIGURED",
    "AUTHENTICATING",
    "SANDBOX",
    "TESTING",
    "ACTIVE",
    "DEGRADED",
    "RATE_LIMITED",
    "AUTH_ERROR",
    "ERROR",
    "DISABLED",
  ]),
  statusMessage: z.string().optional(),
  displayName: z.string().trim().min(1),
  configuration: z.record(z.string(), z.unknown()),
  secretReference: z.string().optional(),
  externalAccountId: z.string().optional(),
  metadata: z.record(z.string(), z.unknown()),
  lastSuccessfulRequestAt: z.string().optional(),
  lastFailedRequestAt: z.string().optional(),
  lastHealthCheckAt: z.string().optional(),
  lastWebhookAt: z.string().optional(),
  consecutiveFailures: z.number().int().nonnegative(),
  createdAt: z.string(),
  updatedAt: z.string(),
});
